[tool.poetry]
name = "duplexer"
version = "0.1.0"
description = ""
authors = ["marijnvanwezel <marijnvanwezel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pypdf = "^5.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
